#docker run -d --name=grafana -p 3000:3000 grafana/grafana
#docker pull grafana/grafana:9.2.6-ubuntu

version: '3.8'
services:
  grafana:
    image: grafana/grafana:9.2.6-ubuntu
    container_name: grafana_ct
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
     # - ./uptime-kuma:/app/data
    #for the moment eliminated to be checked
    ports:
     - 3000:3000
      
    networks:
      - monitoring_nt
        
volumes:
  grafana_data:
    name: grafana_data
    driver: local

networks:
  monitoring_nt:
    external: true
