apiVersion: 1

deleteDatasources:
  - name: Prometheus-cityhunter
    orgId: 1 #par précaution : it should be kept for a year even though we know it is deleted (other laptops can be asleep in the meanwhile) 
              #If Configuration have changed in the meanwhile
  - name: Prometheus-cityhunter-1 
    orgId: 1
  - name: Prometheus-cityhunter-2
    orgId: 1
  - name: Prometheus-S1
    orgId: 1
  - name: Prometheus-S2
    orgId: 1

datasources:

  - name: Prometheus-cityhunter
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus_ct:9090
    version: 1
    editable: false

  - name: Prometheus-S1
    type: prometheus
    access: proxy
    orgId: 1
    url: http://164.90.211.235:9090
    version: 1
    editable: false

  - name: Prometheus-S2
    type: prometheus
    access: proxy
    orgId: 1
    url: http://164.90.238.184:9090
    version: 1
    editable: false